name: niklas
favicon: null
layout_spectrum: 0.07372792903333902
typography_spectrum: 0.13374333223327994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9116235724650323
  lightness: 0.08952992921695113
  saturation: 0.11373867723159492
  rhythmicContrast: 0.0991381355561316
purpose: []
